title: MingKe Li's Homepage
page-top-title: MingKe Li
top-section-bg-text: Computer Science
home-subtitle: MingKe Li&ensp;|&ensp;李明岢
copyright-text: '&copy; MingKe Li 2023-2025. All Rights Reserved.'
